phantomjs:
  image: binux/pyspider:my
  command: phantomjs
result:
  image: binux/pyspider:my
  external_links:
    - mysql
    - rabbitmq
  command: result_worker
processor:
  image: binux/pyspider:my
  external_links:
    - mysql
    - rabbitmq
  command: processor
fetcher:
  image: binux/pyspider:my
  external_links:
    - rabbitmq
  links:
    - phantomjs
  command : fetcher
scheduler:
  image: binux/pyspider:my
  external_links:
    - mysql
    - rabbitmq
  command: scheduler
webui:
  image: binux/pyspider:my
  external_links:
    - mysql
    - rabbitmq
  links:
    - scheduler
    - phantomjs
  command: webui
  ports:
    - "5000:5000"